import {defineConfig} from "rollup";
import fs from "fs";

const version = process.env.SEMANTIC_RELEASE_NEXT_VERSION || JSON.parse(fs.readFileSync('./package.json')).version;

console.log('building version:', version);

const banner = `/**
 * MDParser v${version} - a markdown parser
 * Copyright (c) 2020-${new Date().getFullYear()}, Kiran Parajuli. (GNU Licensed)
 * https://github.com/kiranparajuli589/md-parser
 */

/**
 * DO NOT EDIT THIS FILE
 * The code in this file is generated from files in ./lib/
 */
`;

export default defineConfig([{
	input: 'lib/index.js', output: [{
		file: 'dist/mdp.esm.js', format: 'esm', sourcemap: true, banner
	}, {
		file: 'dist/mdp.min.js', format: 'umd', name: 'mdp', sourcemap: false, banner
	}, {
		file: 'dist/mdp.cjs', format: 'cjs', name: 'marked', sourcemap: true, banner
	}]
}, {
	input: 'lib/mdp.js',
	output: [{
		file: 'dist/mdp.umd.js', format: 'umd', name: 'mdp', sourcemap: true, banner
	}]
}]);
