import { defineConfig } from "rollup"
import fs from "fs"


const version = process.env.SEMANTIC_RELEASE_NEXT_VERSION || JSON.parse(fs.readFileSync("./package.json")).version

console.info("building version:", version)

const banner = `/**
 * MDParser v${version} - a markdown parser
 * Copyright (c) 2020-${new Date().getFullYear()}, Kiran Parajuli. (GNU Licensed)
 * https://github.com/kiranparajuli589/htmlmark
 */

/**
 * DO NOT EDIT THIS FILE
 * The code in this file is generated from files in ./lib/
 */
`

export default defineConfig([{
	input: "lib/index.js", output: [{
		file: "dist/htmlmark.esm.js", format: "esm", sourcemap: true, banner
	}, {
		file: "dist/htmlmark.min.js", format: "umd", name: "htmlmark", sourcemap: false, banner
	}, {
		file: "dist/htmlmark.cjs", format: "cjs", sourcemap: true, name: "htmlmark", banner
	}, {
		file: "dist/htmlmark.umd.js", format: "umd", name: "htmlmark", sourcemap: true, banner
	}]
}])
